### ISSUE TITLE
[Formatting] Hide answers using expandable content notation

### ISSUE THREAD

**Issue by raxhvl** [secureum/RACE#6]
It would be helpful to hide answers using expandable content notation especially when one is trying to review past RACEs for practice. I have often time read the answers, while I continued to read the options. For example:
 
**[Q3] Design flaw(s) of `Wallet` is/are:** \
(A): Missing wallet owner role and appropriate access control \
(B): Inability to rescue stuck tokens \
(C): Assembly usage is unsafe for the Yul IR pipeline \
(D): Calling a `payable` method in a for-loop

<details>
<summary>
Answers
</summary> 
 <b>A</b>
</details>

I'm willing to take this up if it seems useful to the team.

**Comment by secureum** [comment]
Resolved by https://github.com/secureum/RACE/pull/8
